name: sikadu_ortu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.1.0
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  get: 4.6.5
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  lottie: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/fotoimg2.png
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon-ortu.png"
  min_sdk_android: 21 
